package com.tomtom.orbis.comparator.quality;

public enum QualityFlag {
    MISSING_STREET, MISSING_HOUSENUMBER, MISSING_POSTCODE, MISSING_CITY,
    INVALID_HOUSENUMBER_FORMAT, INVALID_POSTCODE_FORMAT, ENCODING_ISSUE,
    DUPLICATE_COORDINATE, DUPLICATE_ADDRESS_TEXT,
    OUTSIDE_TILE, DENSITY_OUTLIER_HIGH, ISOLATED_POINT,
    MCR_UNMATCHED,
    SINGLE_ADDRESS_STREET, UNUSUAL_STREET_NAME
}
